app <- ShinyDriver$new("../../")
app$snapshotInit("mytest")

# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
app$snapshot()
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
app$setInputs(cmciLag = 1)
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
app$setInputs(cmciLag = 3)
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
app$setInputs(cmciLag = 4)
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
app$setInputs(indicator = "CCI")
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
# Input '`plotly_hover-A`' was set, but doesn't have an input binding.
# Input '`plotly_hover-A`' was set, but doesn't have an input binding.
# Input '`plotly_hover-A`' was set, but doesn't have an input binding.
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
# Input '`plotly_hover-A`' was set, but doesn't have an input binding.
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
# Input '`plotly_hover-A`' was set, but doesn't have an input binding.
# Input '`plotly_hover-A`' was set, but doesn't have an input binding.
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
app$setInputs(date_range5 = c("1997-02-05", "2022-10-31"))
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
app$setInputs(cmciLead = 1)
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
app$setInputs(cmciLead = 3)
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
# Input '`plotly_afterplot-A`' was set, but doesn't have an input binding.
# Input '`plotly_relayout-A`' was set, but doesn't have an input binding.
# Input '`plotly_hover-A`' was set, but doesn't have an input binding.
# Input '`plotly_hover-A`' was set, but doesn't have an input binding.
# Input '`plotly_hover-A`' was set, but doesn't have an input binding.
# Input '`plotly_hover-A`' was set, but doesn't have an input binding.
